/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolumesIndexRouteImport } from './routes/volumes.index'
import { Route as NetworksIndexRouteImport } from './routes/networks.index'
import { Route as ImagesIndexRouteImport } from './routes/images.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ContainersIndexRouteImport } from './routes/containers.index'
import { Route as ComposeIndexRouteImport } from './routes/compose.index'
import { Route as ContainersIdRouteImport } from './routes/containers.$id'
import { Route as ComposeNameRouteImport } from './routes/compose.$name'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumesIndexRoute = VolumesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolumesRoute,
} as any)
const NetworksIndexRoute = NetworksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworksRoute,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImagesRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainersRoute,
} as any)
const ComposeIndexRoute = ComposeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComposeRoute,
} as any)
const ContainersIdRoute = ContainersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContainersRoute,
} as any)
const ComposeNameRoute = ComposeNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ComposeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRouteWithChildren
  '/containers': typeof ContainersRouteWithChildren
  '/help': typeof HelpRoute
  '/images': typeof ImagesRouteWithChildren
  '/logs': typeof LogsRoute
  '/networks': typeof NetworksRouteWithChildren
  '/settings': typeof SettingsRoute
  '/volumes': typeof VolumesRouteWithChildren
  '/compose/$name': typeof ComposeNameRoute
  '/containers/$id': typeof ContainersIdRoute
  '/compose/': typeof ComposeIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/volumes/': typeof VolumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/compose/$name': typeof ComposeNameRoute
  '/containers/$id': typeof ContainersIdRoute
  '/compose': typeof ComposeIndexRoute
  '/containers': typeof ContainersIndexRoute
  '/events': typeof EventsIndexRoute
  '/images': typeof ImagesIndexRoute
  '/networks': typeof NetworksIndexRoute
  '/volumes': typeof VolumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compose': typeof ComposeRouteWithChildren
  '/containers': typeof ContainersRouteWithChildren
  '/help': typeof HelpRoute
  '/images': typeof ImagesRouteWithChildren
  '/logs': typeof LogsRoute
  '/networks': typeof NetworksRouteWithChildren
  '/settings': typeof SettingsRoute
  '/volumes': typeof VolumesRouteWithChildren
  '/compose/$name': typeof ComposeNameRoute
  '/containers/$id': typeof ContainersIdRoute
  '/compose/': typeof ComposeIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/volumes/': typeof VolumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compose'
    | '/containers'
    | '/help'
    | '/images'
    | '/logs'
    | '/networks'
    | '/settings'
    | '/volumes'
    | '/compose/$name'
    | '/containers/$id'
    | '/compose/'
    | '/containers/'
    | '/events/'
    | '/images/'
    | '/networks/'
    | '/volumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/logs'
    | '/settings'
    | '/compose/$name'
    | '/containers/$id'
    | '/compose'
    | '/containers'
    | '/events'
    | '/images'
    | '/networks'
    | '/volumes'
  id:
    | '__root__'
    | '/'
    | '/compose'
    | '/containers'
    | '/help'
    | '/images'
    | '/logs'
    | '/networks'
    | '/settings'
    | '/volumes'
    | '/compose/$name'
    | '/containers/$id'
    | '/compose/'
    | '/containers/'
    | '/events/'
    | '/images/'
    | '/networks/'
    | '/volumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposeRoute: typeof ComposeRouteWithChildren
  ContainersRoute: typeof ContainersRouteWithChildren
  HelpRoute: typeof HelpRoute
  ImagesRoute: typeof ImagesRouteWithChildren
  LogsRoute: typeof LogsRoute
  NetworksRoute: typeof NetworksRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  VolumesRoute: typeof VolumesRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volumes/': {
      id: '/volumes/'
      path: '/'
      fullPath: '/volumes/'
      preLoaderRoute: typeof VolumesIndexRouteImport
      parentRoute: typeof VolumesRoute
    }
    '/networks/': {
      id: '/networks/'
      path: '/'
      fullPath: '/networks/'
      preLoaderRoute: typeof NetworksIndexRouteImport
      parentRoute: typeof NetworksRoute
    }
    '/images/': {
      id: '/images/'
      path: '/'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof ImagesRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/': {
      id: '/containers/'
      path: '/'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/compose/': {
      id: '/compose/'
      path: '/'
      fullPath: '/compose/'
      preLoaderRoute: typeof ComposeIndexRouteImport
      parentRoute: typeof ComposeRoute
    }
    '/containers/$id': {
      id: '/containers/$id'
      path: '/$id'
      fullPath: '/containers/$id'
      preLoaderRoute: typeof ContainersIdRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/compose/$name': {
      id: '/compose/$name'
      path: '/$name'
      fullPath: '/compose/$name'
      preLoaderRoute: typeof ComposeNameRouteImport
      parentRoute: typeof ComposeRoute
    }
  }
}

interface ComposeRouteChildren {
  ComposeNameRoute: typeof ComposeNameRoute
  ComposeIndexRoute: typeof ComposeIndexRoute
}

const ComposeRouteChildren: ComposeRouteChildren = {
  ComposeNameRoute: ComposeNameRoute,
  ComposeIndexRoute: ComposeIndexRoute,
}

const ComposeRouteWithChildren =
  ComposeRoute._addFileChildren(ComposeRouteChildren)

interface ContainersRouteChildren {
  ContainersIdRoute: typeof ContainersIdRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
}

const ContainersRouteChildren: ContainersRouteChildren = {
  ContainersIdRoute: ContainersIdRoute,
  ContainersIndexRoute: ContainersIndexRoute,
}

const ContainersRouteWithChildren = ContainersRoute._addFileChildren(
  ContainersRouteChildren,
)

interface ImagesRouteChildren {
  ImagesIndexRoute: typeof ImagesIndexRoute
}

const ImagesRouteChildren: ImagesRouteChildren = {
  ImagesIndexRoute: ImagesIndexRoute,
}

const ImagesRouteWithChildren =
  ImagesRoute._addFileChildren(ImagesRouteChildren)

interface NetworksRouteChildren {
  NetworksIndexRoute: typeof NetworksIndexRoute
}

const NetworksRouteChildren: NetworksRouteChildren = {
  NetworksIndexRoute: NetworksIndexRoute,
}

const NetworksRouteWithChildren = NetworksRoute._addFileChildren(
  NetworksRouteChildren,
)

interface VolumesRouteChildren {
  VolumesIndexRoute: typeof VolumesIndexRoute
}

const VolumesRouteChildren: VolumesRouteChildren = {
  VolumesIndexRoute: VolumesIndexRoute,
}

const VolumesRouteWithChildren =
  VolumesRoute._addFileChildren(VolumesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposeRoute: ComposeRouteWithChildren,
  ContainersRoute: ContainersRouteWithChildren,
  HelpRoute: HelpRoute,
  ImagesRoute: ImagesRouteWithChildren,
  LogsRoute: LogsRoute,
  NetworksRoute: NetworksRouteWithChildren,
  SettingsRoute: SettingsRoute,
  VolumesRoute: VolumesRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
